fix: cloudfront.tf Route53 zone 인덱스 에러 수정
data.aws_route53_zone.main이 count를 사용하므로 [0] 인덱스 접근 필요

변경사항:
- aws_route53_record.cdn_cert_validation: zone_id에 [0] 추가
- aws_route53_record.cdn: zone_id에 [0] 추가

에러 메시지:
  Error: Missing resource instance key
  Because data.aws_route53_zone.main has "count" set,
  its attributes must be accessed on specific instances.